routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Crypt;

//All the frontend goes here
Route::get('/', function () {
	$jobcategories = \App\JobCategory::all();
    return view('master', compact('jobcategories'));
})->name('homepage');



//Route::get('/sms', function () {
//	$nexmo = app('Nexmo\Client');
//	$nexmo->message()->send([
//		'to' 	=> '94773669783',
//		'from' 	=> '94773669783',
//		'text' 	=> 'Be aware of this message!'
//	]);
//});

Route::get('/api/v1/job_post/slugs', function (){
	return \App\JobPost::all();
});

Route::get('/job_post/user/{user}', ['as' => 'jobpost.slug.user', 'uses' => 'JobPostViewController@getSlugPerUser']);

Route::get('/api/v1/user_info', function (){
	if(isset($_GET["password"]) && isset($_GET["email"])){
		$password = $_GET["password"];
		$email = $_GET["email"];

		if(Auth::attempt(['email' => $email, 'password' => $password])){
			$user = \App\User::where('email', '=', $email)->first();
			return "welcome";
		}else{
			//error
			return 'Wrong email or password being provided!';
		}
	}else{
		return 'email or password not being set';
	}
});

Route::get('/api/v1/job_search/data', function (){
	$job_posts = \App\JobPost::with('job_categories', 'comments', 'applied_by')->get();

	foreach ($job_posts as $job_post)
	{
		$job_seekers[] = $job_post->applied_by;
	}

	foreach ($job_seekers as $job_seeker)
	{
		$resumes[] = $job_seeker;
	}

	return $job_posts;
});
//Route::get('/job_search', ['as' => 'jobpost.search', 'uses' => 'JobPostViewController@getSearch']);


Route::get('/job_post/{slug}', ['as' => 'jobpost.single', 'uses' => 'JobPostViewController@getSingle']);
Route::get('/job_category/{jobcategory}/job_posts', ['as' => 'category.jobposts', 'uses' => 'JobPostViewController@getAllForCategory']);

Route::group(['middleware' => ['simpleauth'], 'prefix' => '/api/v1'], function() {
	Route::resource('/jobposts', 'Api\JobPostsController', array('only' => array('index')));
});


//All the backend goes here

Route::group(['middleware' => ['web', 'auth', 'roles'], 'prefix' => '/admin', 'roles' => ['Admin']], function() {
    Route::get('/dashboard', function () {
        return view('backend.dashboard');
    })->name('admindashboard');
    Route::resource('/jobcategory', 'JobCategoryController');
//    Route::resource('/users', 'UserController');
});



Route::group(['middleware' => ['web', 'auth', 'roles'], 'roles' => ['Admin', 'Employer', 'Job Seeker']], function() {
	Route::resource('/jobpost', 'JobPostController', ['only' => ['index']]);
	//    Route::resource('/users', 'UserController');
});

Route::group(['middleware' => ['web', 'auth', 'roles'], 'roles' => ['Admin', 'Employer']], function() {
	Route::resource('/jobpost', 'JobPostController', ['except' => ['index']]);
	Route::get('/jobpost/{id}/requirements', 'JobPostRequirementController@getPage');
	Route::get('/jobpost/{id}/requirements/data', 'JobPostRequirementController@getRequirements');
	Route::post('/jobpost/{id}/requirements', 'JobPostRequirementController@saveRequirements');
	//    Route::resource('/users', 'UserController');

	//to view rank
	Route::get('/jobpost/{id}/view_rank', 'JobPostController@getRank');

	//delete this view Edu
	Route::get('/jobpost/{id}/view_edu', 'JobPostController@getEdu');
});

Route::group(['middleware' => ['web', 'auth'], 'prefix' => '/jobpost'], function() {
	Route::post('/{jobpost}/comments', 'JobPostCommentController@save', function (){

	})->name('jobpost.comment.save');
});

Route::group(['middleware' => ['web', 'auth']], function() {
	Route::resource('/employer_profiles', 'EmployerProfileController');
	Route::get('/profile/{slug}', ['as' => 'profile.index', 'uses' => 'ProfileController@getProfile']);
	Route::post('/profile/image', ['as' => 'profile.avatar', 'uses' => 'ProfileController@updateAvatar']);
	Route::resource('/job_seeker_profiles', 'JobSeekerProfileController');
//	Route::get('/job_seeker_profiles/{job_seeker_profile}/resume', ['as' => 'job_seeker_profiles.resume', 'uses' => 'JobSeekerProfileController@resume']);
	//same new for above
	Route::get('/job_seeker_profiles/{job_seeker_profile}/resume', ['as' => 'job_seeker_profiles.resume', 'uses' => 'JobSeekerProfileController@getResume']);
	Route::get('/job_seeker_profiles/{job_seeker_profile}/resume/create', ['as' => 'job_seeker_profiles.createresume', 'uses' => 'JobSeekerProfileController@resumeNew']);
	Route::get('/job_seeker_profiles/{job_seeker_profile}/resume/data', ['as' => 'job_seeker_profiles.resume.data', 'uses' => 'JobSeekerProfileController@resumeData']);
	Route::post('/job_seeker_profiles/resume', ['as' => 'job_seeker_profiles.postresume', 'uses' => 'JobSeekerProfileController@resumeSave']);
	Route::post('/apply_job_post/{job_post}/profile/{job_seeker_profile}', ['as' => 'job_seeker_profiles.job_post.apply', 'uses' => 'JobSeekerProfileController@applyJobPost']);

//	Route::post('/apply_job_post/{job_post}/profile/{job_seeker_profile}', ['as' => 'job_seeker_profiles.job_post.edu', 'uses' => 'JobSeekerProfileController@applyJobPostEdu']);
	//delete the below route after testing textmining
	Route::post('/apply_job_post/{job_post}/profile/{job_seeker_profile}/textmining', ['as' => 'job_seeker_profiles.job_post.runtextmining', 'uses' => 'JobSeekerProfileController@runSkillPoints']);
	Route::post('/apply_job_post/{job_post}/profile/{job_seeker_profile}/delete', ['as' => 'job_seeker_profiles.job_post.withdraw', 'uses' => 'JobSeekerProfileController@withdrawJobPost']);
});


Auth::routes();

//Route::get('/home', 'HomeController@index');

Route::group(['middleware' => ['web', 'auth', 'roles'], 'prefix' => 'api/v1', 'roles' => ['Admin']], function() {
    Route::resource('/users', 'Api\UserController', ['only' => ['index', 'update', 'store', 'destroy']]);
});


Route::get('/protected', ['middleware' => ['auth', 'admin'], function() {
    return "this page requires that you be logged in and an Admin";
}]);

app/JobCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JobCategory extends Model
{
    //
    protected $table = 'job_categories';

    protected $fillable = [
        'name', 'details'
    ];

	protected $hidden = array('created_at', 'updated_at', );

	public function job_posts()
	{
		return $this->belongsToMany('App\JobPost');
	}

//	public function getRouteKeyName()
//	{
//		return 'name';
//	}

}

app/Http/Controllers/JobCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\JobCategoryRequest;
use App\JobCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class JobCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $jobcategories = JobCategory::all();
        return view('backend.admin.jobcategory.index', compact('jobcategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('backend.admin.jobcategory.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param JobCategoryRequest $categoryRequest
     * @return \Illuminate\Http\Response
     * @internal param Request $request
     */
    public function store(Request $request)
    {
        //
        $job_category = JobCategory::create([
            'name' => $request->input('name'),
            'details' => $request->input('details'),
        ]);

        return redirect()->route('jobcategory.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $jobcat = JobCategory::where('id', '=', $id)->first();
        return view('backend.admin.jobcategory.edit', compact('jobcat'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        JobCategory::find($id)->update($request->all());
        return redirect()->route('jobcategory.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $category = JobCategory::find($id);

        $category->job_posts()->detach();

        $category->delete();
		flash()->overlay('Job Category Delete!', 'Job Category Deleted Successfully', 'error');
        return redirect()->route('jobcategory.index');
    }
}

resources/views/backend/admin/jobcategory/create.blade.php
@extends('backend.layout')
<!-- Content Header (Page header) -->

@section('body')
    <section class="content-header">
        <h1>
            Dashboard
            <small>Version 2.0</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-warning">
                    <div class="box-header with-border">
                        <center><h3 class="box-title">Add Job Category</h3></center>
                        <div class="box-tools pull-right">
                            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        </div>
                    </div><!-- /.box-header --><!-- /.box-header -->
                    <div class="box-body">
                        <form action="{{ route('jobcategory.store') }}" method="post" id="jobcategoryform">
                            <div class="form-group row {{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="name" class="col-xs-4">Name: </label>
                                <div class="col-xs-8">
                                    <input type="text" id="name" name="name" class="form-control" placeholder="Job Category" value="{{ old('name') }}">
                                    @if ($errors->has('name'))
                                        <span class="help-block">
									        <strong>{{ $errors->first('name') }}</strong>
							            </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group row {{ $errors->has('details') ? ' has-error' : '' }}">
                                <label for="details" class="col-xs-4">Details: </label>
                                <div class="col-xs-8">
                                    <textarea name="details" id="details" class="form-control col-xs-12">{{ old('details') }}</textarea>
                                    @if ($errors->has('details'))
                                        <span class="help-block">
									        <strong>{{ $errors->first('details') }}</strong>
							            </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-xs-4 pull-right">
                                    <button type="submit" class="btn btn-primary btn-sm" style="float: right">Add New</button>
                                </div>
                            </div>
                            {{ csrf_field() }}
                        </form>
                    </div><!-- /.box-body -->
                    <div class="box-footer">
                        &nbsp;
                    </div>
                </div><!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

        <!-- Main row -->
        <div class="row">


        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection


@section('pagescripts')
    <!-- Laravel Javascript Validation -->
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\JobCategoryRequest', '#jobcategoryform') !!}
@endsection

resources/views/backend/admin/jobcategory/edit.blade.php
@extends('backend.layout')
<!-- Content Header (Page header) -->

@section('body')
    <section class="content-header">
        <h1>
            Dashboard
            <small>Version 2.0</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-warning">
                    <div class="box-header with-border">
                        <center><h3 class="box-title">Add Job Category</h3></center>
                        <div class="box-tools pull-right">
                            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        </div>
                    </div><!-- /.box-header --><!-- /.box-header -->
                    <div class="box-body">
                        {!! Form::model($jobcat, array('method' => 'PUT', 'route' => ['jobcategory.update', $jobcat->id], 'id' => 'jobcategoryform')) !!}
                            <div class="form-group row {{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="name" class="col-xs-4">Name: </label>
                                <div class="col-xs-8">
                                    <input type="text" id="name" name="name" class="form-control" placeholder="Job Category" value="{{ $jobcat->name }}">
                                    @if ($errors->has('name'))
                                        <span class="help-block">
									        <strong>{{ $errors->first('name') }}</strong>
							            </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group row {{ $errors->has('details') ? ' has-error' : '' }}">
                                <label for="details" class="col-xs-4">Details: </label>
                                <div class="col-xs-8">
                                    <textarea name="details" id="details" class="form-control col-xs-12">{{ $jobcat->details }}</textarea>
                                    @if ($errors->has('details'))
                                        <span class="help-block">
									        <strong>{{ $errors->first('details') }}</strong>
							            </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-xs-4 pull-right">
                                    <button type="submit" class="btn btn-primary btn-sm" style="float: right"> Update</button>
                                </div>
                            </div>
                            {!! Form::hidden('id', $jobcat->id) !!}
                            {{ csrf_field() }}
                        {!! Form::close()  !!}
                    </div><!-- /.box-body -->
                    <div class="box-footer">
                        &nbsp;
                    </div>
                </div><!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

        <!-- Main row -->
        <div class="row">


        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection


@section('pagescripts')
    <!-- Laravel Javascript Validation -->
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\JobCategoryRequest', '#jobcategoryform') !!}
@endsection

resources/views/backend/admin/jobcategory/index.blade.php
@extends('backend.layout')
<!-- Content Header (Page header) -->

@section('body')
    {{--<section class="content-header">--}}
        {{--<h1>--}}
            {{--Dashboard--}}
            {{--<small>Version 2.0</small>--}}
        {{--</h1>--}}
        {{--<ol class="breadcrumb">--}}
            {{--<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>--}}
            {{--<li class="active">Dashboard</li>--}}
        {{--</ol>--}}
    {{--</section>--}}

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="row">
                    <div class="col-xs-12">
                        <h4>Add Job Category</h4>
                    </div>
                </div>
                <div class="well">
                    <form action="{{ route('jobcategory.store') }}" method="post" id="jobcategoryform">
                        <div class="form-group row {{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-xs-4">Name: </label>
                            <div class="col-xs-8">
                                <input type="text" id="name" name="name" class="form-control" placeholder="Job Category" value="{{ old('name') }}">
                                @if ($errors->has('name'))
                                    <span class="help-block">
									        <strong>{{ $errors->first('name') }}</strong>
							            </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row {{ $errors->has('details') ? ' has-error' : '' }}">
                            <label for="details" class="col-xs-4">Details: </label>
                            <div class="col-xs-8">
                                <textarea name="details" id="details" class="form-control col-xs-12">{{ old('details') }}</textarea>
                                @if ($errors->has('details'))
                                    <span class="help-block">
									        <strong>{{ $errors->first('details') }}</strong>
							            </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-xs-4 pull-right">
                                <button type="submit" class="btn btn-primary btn-sm" style="float: right">Add New</button>
                            </div>
                        </div>
                        {{ csrf_field() }}
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">

                <div class="box box-warning">
                    <div class="box-header with-border">
                        <center><h3 class="box-title">Job Categories</h3></center>
                        <div class="box-tools pull-right">
                            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        </div>
                    </div><!-- /.box-header --><!-- /.box-header -->
                    <div class="box-body">
                        <a href="{{ route('jobcategory.create') }}" style="margin-bottom: 10px" class="btn btn-info pull-left"> Create</a>
                        <table id="datatable" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Job Category</th>
                                <th>Description</th>
                                <th>No of Posts</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($jobcategories as $category)
                                <tr class="tablerow" data-categoryid="{{$category->id}}">
                                    <td>{{$category->id}}</td>
                                    <td>{{$category->name}}</td>
                                    <td>{{substr($category->details, 0, 30)}} <span style="color: red">{{ strlen($category->details) > 30 ? "..." : "" }}</span></td>
                                    <td>{{$category->job_posts()->count()}}</td>
                                    <td clexass="tablecolumn row">
                                        <div class="col-md-6">
                                            <a class="btn btn-warning btn-xs" href="{{ route('jobcategory.edit', $category->id) }}"><i class="fa fa-pencil"> Edit</i></a>
                                        </div>
                                        <div class="col-md-6">
                                            {!! Form::open(['method' => 'DELETE', 'route' => ['jobcategory.destroy', $category->id], 'onsubmit' => 'return ConfirmDelete()']) !!}
                                            {!! Form::button('<i class="fa fa-trash"> Delete</i>', array('type' => 'submit', 'class' => 'btn btn-danger btn-xs')) !!}
                                            {!! Form::close() !!}
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>#</th>
                                <th>Job Category</th>
                                <th>Description</th>
                                <th>No of Posts</th>
                                <th>Action</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div><!-- /.box-body -->
                    <div class="box-footer">
                        &nbsp;
                    </div>
                </div><!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

        <!-- Main row -->
        <div class="row">


        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection

@section('pagescripts')
    <script>
        $(function () {
            $("#datatable").DataTable({
                scrollX: true,
                lengthMenu: [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]]
            });
        });
    </script>
    <!-- Laravel Javascript Validation -->
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\JobCategoryRequest', '#jobcategoryform') !!}
    <script>
        $(".deleteForm").on("submit", function(){
            return confirm("Do you want to delete this item?");
        });
    </script>
    {{--Flash function--}}
    @include('flash')

@endsection